# Generated by Django 2.2 on 2019-04-17 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190417_1730'),
        ('members', '0002_auto_20190415_1719'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
