# Generated by Django 2.2 on 2019-04-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190419_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='태그명'),
        ),
    ]
