# Generated by Django 2.2 on 2019-04-19 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190419_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='_html',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='태그가 HTML화된 댓글 내용'),
            preserve_default=False,
        ),
    ]
